### ISSUE TITLE
Twitter and Facebook login hangs the application

### ISSUE THREAD

**Issue by zscholl** [BabylonianTeam/Babylonians#42]
### Description

On the initial bootup of the application. Clicking the "Twitter Login" or "Facebook Login" button hangs the application.

The features are missing as shown in #33, but clicking the button should not halt any further operations. 

Here is a screenshot of the screen after clicking the "Twitter Login" or "Facebook Login" button.

![screen shot 2016-04-26 at 12 30 16 pm](https://cloud.githubusercontent.com/assets/8786230/14828123/29ecbeaa-0bab-11e6-93a4-c5d3c8c4fe6b.png)
### Severity

Critical
### Suggestions

Either take out the login button or give the user feedback saying that the action failed.

**Comment by m4a11205** [comment]
The functions are not implemented before. They're now added in master branch.
