### ISSUE TITLE
Lack of styling/unfriendly UI

### ISSUE THREAD

**Issue by poofelt** [BabylonianTeam/Babylonians#45]
### **Description:**

The Application has little styling to it. I know functionality is key, but lack of buttons and styled UI makes the application harder to use.
### **Severity:**

 If you plan on working on this application after the class the look of it is extremely important and is of critical severity. 
### **Suggestions:**

Adding a few buttons and a few text fields describing things would be an easy start that would go a long way.

**Comment by wandonye** [comment]
could you be specific where and which buttons are missing?

update:
No concrete suggestion in this issue report, thus closed
