### ISSUE TITLE
Learners should not be able to edit global courses

### ISSUE THREAD

**Issue by cpvandehey** [BabylonianTeam/Babylonians#49]
### Description

When looking at "my courses" as a learner, you are given the privilege to edit and delete aspects of a coarse that other users see.
### Severity

Blocker status because of the ability to trash all of every course.
### Suggestion

Set user level privileges as a learner.

**Comment by wandonye** [comment]
this was probably fixed immediately after we created test branch.
The later master version doesn't have this issue
