### ISSUE TITLE
Password changes show up in plain-text

### ISSUE THREAD

**Issue by zscholl** [BabylonianTeam/Babylonians#52]
### Description

Under the "more" tab, when I attempt to change my password, all of my password inputs are shown in plain-text. 

Here is a screenshot:
![screen shot 2016-04-26 at 3 55 48 pm](https://cloud.githubusercontent.com/assets/8786230/14833962/6711e532-0bc7-11e6-8918-b47cbe73e681.png)
### Severity

Moderate
### Suggestions

Modify the code to show obscured characters when entering a password.

**Comment by m4a11205** [comment]
fixed
