### ISSUE TITLE
All users share the same course publication and draft

### ISSUE THREAD

**Issue by deyishi** [BabylonianTeam/Babylonians#53]
### Description

After I created a new user and logged in as that user, I could still access the course publication and draft of other users. 
### Severity

BLOCKER  **This is a very severe bug, you cannot ship with this**
### Cause

incorrect backend implementation

**Comment by wandonye** [comment]
This is because these views are using the base node of all courses.
The node for Creator's created courses and leaners' purchased courses are missing for certain users. 
Will be fixed soon
