### ISSUE TITLE
Course price resets to 0 when it is published as draft

### ISSUE THREAD

**Issue by zscholl** [BabylonianTeam/Babylonians#58]
### Description

If I first publish a course with a course price, then re-edit the course, without changing the course price, if I "Save to draft" then the course price resets to 0. 
### Severity

Moderate
### Suggestions

Make sure when you save a new copy of the course that you copy all of the current values.

**Comment by wandonye** [comment]
fixed
https://github.com/BabylonianTeam/Babylonians/commit/73b110f7565f6ff027bc9343380a97f11a71aa2c
