### ISSUE TITLE
Recording feature lacking feedback

### ISSUE THREAD

**Issue by cpvandehey** [BabylonianTeam/Babylonians#59]
### Description

A user is able to successfully record a sound clip, but the interface is lacking tons of feedback to guide the process. First and foremost the recording button needs a better status symbol when you are recording. After the recording is complete, there is a fair amount of processing involved before it goes into the course. A loading screen would be beneficial to notify the user that it is actually processing.
### Severity

Trivial.
### Suggestion

Big, centralized notifications to guide the user.

**Comment by wandonye** [comment]
TODO: use ProgressHUD to push a "recording" message

**Comment by wandonye** [comment]
This is done: use ProgressHUD to push a "recording" message
As to the other half of suggestion: we are planing on a better solution, which will cache the audio/image file first before uploading. This will reduce the loading time significantly.
