### ISSUE TITLE
Course tags do not save

### ISSUE THREAD

**Issue by zscholl** [BabylonianTeam/Babylonians#60]
### Description

When I edit a course and add course tags to it then save as draft or publish, none of the tags save to the course so I can't see them when I view the course again.
### Severity

Moderate
### Suggestions

Make sure all fields are being saved on any of these saving operations.

**Comment by wandonye** [comment]
fixed
https://github.com/BabylonianTeam/Babylonians/commit/73b110f7565f6ff027bc9343380a97f11a71aa2c
