### ISSUE TITLE
Saving a published course to draft does not show up in drafts

### ISSUE THREAD

**Issue by zscholl** [BabylonianTeam/Babylonians#61]
### Description

If I open a published course and "Save to draft" the course does not show up in the drafts column.
### Severity

Moderate
### Suggestions

Fix it.

**Comment by wandonye** [comment]
A note to myself: check the course status, if published, then replace the button "save to draft" with "make a copy" or "duplicate". The corresponding function should make a copy of the course without changing anything of the original course.
