### ISSUE TITLE
Course Title changes

### ISSUE THREAD

**Issue by poofelt** [BabylonianTeam/Babylonians#62]
### Description

When you change the course title of a course it only saves it in the "setings" and not in the "my course" tab or main tab. 
### Severity

Trivial because if you want to change your name to a more descriptive title is impossible.
### Suggestions

Have the "Setings" and the tabs share the same title variable.

P.S. Settings is spelled wrong as "setings"

**Comment by jxu62** [comment]
Course title can save in the my course draft. 
Fix the typo with "setings"
