### ISSUE TITLE
Long course titles display overtop of the price

### ISSUE THREAD

**Issue by zscholl** [BabylonianTeam/Babylonians#66]
### Description

If a course title is long enough it obscures the price of the course.
![screen shot 2016-04-26 at 4 38 12 pm](https://cloud.githubusercontent.com/assets/8786230/14835079/94f38b12-0bcd-11e6-8434-075129a7ff17.png)
### Severity

Low
### Suggestions

Write some formatting rules to overcome this issue.

**Comment by wandonye** [comment]
Found this in main view of both learner side and creator side.
now fixed
