### ISSUE TITLE
Auto Correct In Odd Places

### ISSUE THREAD

**Issue by cpvandehey** [BabylonianTeam/Babylonians#67]
### Description

Auto correct is a convenient feature in certain fields. Passwords may not be the best choice to include auto correct.
### Severity

Trivial.
### Suggestion

Make the field to avoid auto correct.

![screen shot 2016-04-26 at 4 40 42 pm](https://cloud.githubusercontent.com/assets/7979252/14835127/d01b33ac-0bcd-11e6-9051-57a08c55088e.png)

**Comment by m4a11205** [comment]
fixed
