### ISSUE TITLE
Change password failure

### ISSUE THREAD

**Issue by cpvandehey** [BabylonianTeam/Babylonians#70]
### Description

While attempting a basic password change, I am told that my original does not match (which is 100% certainly wrong).
### Severity

Trivial.
### Suggestion

Adjust the change password field to adjust.

![Uploading Screen Shot 2016-04-26 at 4.44.33 PM.png…]()

![screen shot 2016-04-26 at 4 44 33 pm](https://cloud.githubusercontent.com/assets/7979252/14835246/60e5b6b4-0bce-11e6-8d9f-493a18c59162.png)

**Comment by m4a11205** [comment]
It works perfect on master branch. Maybe there's some merging issues when creating the test branch.
