### ISSUE TITLE
Changing Email

### ISSUE THREAD

**Issue by poofelt** [BabylonianTeam/Babylonians#71]
### Description

Changing your Email in the account section of the "More..." tab causes problems throughout the application. First, you can change your email to whatever you want like \* or paul, so there is no authentication or checking. Second, when you change your email and log out and try to log back in you can't use the new email you have to use the old. When you sign in with the old email it says your email is the new one.
### Severity

Critical because you cannot change your email.
### Suggestion

Make sure you can only change your email to an acceptable email and then make sure to change the global email variable to the new email so you can use it when you log in.

**Comment by m4a11205** [comment]
It has nothing to do with global email variable. The root cause is that Firebase takes the user's email as login account, where Firebase stores the account and password in another database which is more secured. To update an email, we have to update two databases instead of one.
